# Generated by Django 5.2.12 on 2026-04-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_freelance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
