# Generated by Django 5.2.12 on 2026-06-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_freelance_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='descricao',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
